In [36]:
import os
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

from sklearn import decomposition, cluster

from sklearn.decomposition import PCA, IncrementalPCA
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np
import pandas as pd
import polyglot
from polyglot.text import Text, Word
import random


print(__doc__)

__file__ = os.getcwd()
dirname = os.path.dirname(__file__)
input_file = os.path.join(dirname, 'scripts\\data\\dogodki100inglavnekategorije_strippedOnlySlov.csv')
df = pd.read_csv(input_file, header = 0)
original_headers = list(df.columns.values)
data_kats = df['kategorije_nazivi']


vectorizer = CountVectorizer(analyzer='word')
X = vectorizer.fit_transform(data_kats)
print(vectorizer.get_feature_names())
print(X.toarray())
print(vectorizer.vocabulary_)
print(vectorizer.stop_words_)

Automatically created module for IPython interactive environment
['art', 'causes', 'comedy', 'concert', 'dance', 'film', 'food', 'health', 'literature', 'music', 'other', 'party', 'sports', 'tasting', 'theater', 'volunteering', 'wellness']
[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [1 0 0 ... 0 0 0]]
{'causes': 1, 'party': 11, 'other': 10, 'music': 9, 'concert': 3, 'volunteering': 15, 'comedy': 2, 'theater': 14, 'literature': 8, 'dance': 4, 'art': 0, 'film': 5, 'sports': 12, 'wellness': 16, 'food': 6, 'health': 7, 'tasting': 13}
set()
